name: lint

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  ament_lint_general:
    runs-on: ${{ matrix.os }}
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ros_distribution: [galactic]
        linter: [copyright, xmllint]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Linter
        uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: ${{ matrix.ros_distribution }}
          linter: ${{ matrix.linter }}
          package-name: |
            p9n_interface
            p9n_example
            p9n_test

  ament_lint_python:
    runs-on: ${{ matrix.os }}
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ros_distribution: [galactic]
        linter: [pep257, flake8]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Linter
        uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: ${{ matrix.ros_distribution }}
          linter: ${{ matrix.linter }}
          package-name: |
            p9n_interface
            p9n_example
            p9n_test
